name: Test

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Netlify
        uses: netlify/actions/cli@master
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'sbt'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Deploy site
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: sbt "set scalaJSStage in Global := FullOptStage" deploy
